name: Our CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "my_var=some-value" >> $GITHUB_OUTPUT
      - run: echo ${{ steps.step1.outputs.my_var }}
      - run: echo "Hello world"

  test:
    needs: hello
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.12"]
        include:
          - os: macos-latest
            python-version: "3.11"
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: python -m pip install .[test]
      - name: Run tests
        run: python -m pytest -v

  test-containers:
    runs-on: ubuntu-latest
    container: ${{ matrix.distro }}
    strategy:
      matrix:
        distro: ["debian", "archlinux"]
      fail-fast: false
    steps:
      - run: cat /etc/os-release
      - if: matrix.distro == 'archlinux'
        run: |
          echo "This is Arch"
          mkdir
      - run: echo "This will not run"
      - if: failure()
        run: echo "There was an error"
