name: My CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo "Hello World"
      
  test:
    name: Run tests
    strategy:
      matrix:
        os: ["ubuntu-latest","windows-latest"]
        python-version: ["3.9","3.13"]
        include:
          - os: "macos-latest"
          - python-version: '3.11'
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install package
        run: pip install .[test]
      - name: Run Pytest
        run: python -m pytest -v


